//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFM.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CFM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Block.
        /// </summary>
        internal static string ConverterBlock {
            get {
                return ResourceManager.GetString("ConverterBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsupported combination of units of measurement..
        /// </summary>
        internal static string ConverterExceptionArg {
            get {
                return ResourceManager.GetString("ConverterExceptionArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shulker.
        /// </summary>
        internal static string ConverterShulker {
            get {
                return ResourceManager.GetString("ConverterShulker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stack.
        /// </summary>
        internal static string ConverterStack {
            get {
                return ResourceManager.GetString("ConverterStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на stacks.
        /// </summary>
        internal static string ConverterStacks {
            get {
                return ResourceManager.GetString("ConverterStacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на units.
        /// </summary>
        internal static string ConverterUnits {
            get {
                return ResourceManager.GetString("ConverterUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string MainExit {
            get {
                return ResourceManager.GetString("MainExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        internal static string MainFormFile {
            get {
                return ResourceManager.GetString("MainFormFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mini-window.
        /// </summary>
        internal static string MainFormMiniWindow {
            get {
                return ResourceManager.GetString("MainFormMiniWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reference.
        /// </summary>
        internal static string MainFormReference {
            get {
                return ResourceManager.GetString("MainFormReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remainder.
        /// </summary>
        internal static string MainFormRemainder {
            get {
                return ResourceManager.GetString("MainFormRemainder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Converter for Minecraft.
        /// </summary>
        internal static string MainFormTitle {
            get {
                return ResourceManager.GetString("MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About us.
        /// </summary>
        internal static string ReferenceAboutUs {
            get {
                return ResourceManager.GetString("ReferenceAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mail for communication:.
        /// </summary>
        internal static string ReferenceEmail {
            get {
                return ResourceManager.GetString("ReferenceEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reference.
        /// </summary>
        internal static string ReferenceFormTitle {
            get {
                return ResourceManager.GetString("ReferenceFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application version:.
        /// </summary>
        internal static string ReferenceVersion {
            get {
                return ResourceManager.GetString("ReferenceVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string SettingsBtnCancel {
            get {
                return ResourceManager.GetString("SettingsBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string SettingsFormTitle {
            get {
                return ResourceManager.GetString("SettingsFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Larger font size.
        /// </summary>
        internal static string SettingsLabelBigSizeFont {
            get {
                return ResourceManager.GetString("SettingsLabelBigSizeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Design.
        /// </summary>
        internal static string SettingsLabelDesign {
            get {
                return ResourceManager.GetString("SettingsLabelDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language:.
        /// </summary>
        internal static string SettingsLabelLanguage {
            get {
                return ResourceManager.GetString("SettingsLabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other.
        /// </summary>
        internal static string SettingsLabelOther {
            get {
                return ResourceManager.GetString("SettingsLabelOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme for app:.
        /// </summary>
        internal static string SettingsLabelTheme {
            get {
                return ResourceManager.GetString("SettingsLabelTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main.
        /// </summary>
        internal static string SettingsTabMain {
            get {
                return ResourceManager.GetString("SettingsTabMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        internal static string SmallWindowBack {
            get {
                return ResourceManager.GetString("SmallWindowBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        internal static string ThemeLangDark {
            get {
                return ResourceManager.GetString("ThemeLangDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        internal static string ThemeLangLight {
            get {
                return ResourceManager.GetString("ThemeLangLight", resourceCulture);
            }
        }
    }
}
